import type { Metadata } from "next"
import { Montserrat } from 'next/font/google'
import Navigation from "./_components/Navigation"
import "./globals.css"

export const metadata: Metadata = {
  title: "Jeff Sahim - Software Developer",
  description: "Generated by create next app",
  icons: {
    icon: '/images/mini-logo.png',
  }
}

const montserrat = Montserrat({
  subsets: ['latin'],
})

export default function RootLayout({children}: Readonly<{children: React.ReactNode;}>) {
  return (
    <html lang="en">
      <body>
        <Navigation />
        <main className='pt-28 flex flex-col items-center h-[100vh]'>
          {children}
        </main>
      </body>
    </html>
  )
}
